(function(){
"use strict";
window.ODCV_SKILL_BODIES = {
  "product-thinking": {
    "title_en": "Product Thinking & Strategy",
    "title_ru": "Product Thinking и стратегия",
    "body_en": "Designing outcomes, not screens 9+ yrs product experience 20+ products shipped 3 verticals: Fintech · SaaS · AI Most designers hand off a Figma file and call it done. I stay until the metric moves. My background is unusual: a marketing degree in Management & Marketing gave me the business vocabulary before I ever opened a design tool. That means I've always thought in funnels, conversion rates, and customer lifetime value — not just in layouts. When I join a product team, I'm not waiting for someone to translate the business goal into a design brief. I write the brief. In practice this looks like: running JTBD workshops before wireframes exist, co-owning the roadmap prioritization with PM using RICE/ICE, and being the person who asks \"what's the success metric for this screen?\" before the design review. Project context →  Gate19 — redesigned payment format flow from first principles using user interviews + funnel data. A/B tested 3 formats. Conversion on new user activation increased measurably. One format became the default across the entire 20-product platform.",
    "body_ru": "Дизайню результат, а не экраны. 9+ лет продуктового опыта, 20+ продуктов, вертикали Fintech · SaaS · AI. Маркетинговое образование дало язык бизнеса до первого мастера в Figma: воронки, конверсии, LTV. На практике: JTBD до вайрфреймов, совместный роадмап с PM через RICE/ICE, вопрос про success metric до ревью. Кейс Gate19 — платёжные форматы с нуля: интервью + воронка, A/B трёх форматов, рост активации; победивший формат стал дефолтом на платформе из 20 продуктов."
  },
  "ux-research": {
    "title_en": "UX Research & Validation",
    "title_ru": "UX-исследования и валидация",
    "body_en": "Marketing brain + designer eye = research that sticks A/B tested 100+ landing variants Qualitative + quant combined Amplitude · Mixpanel · Hotjar Here's something I don't see on many designer profiles: I studied marketing before UX. That's not a footnote — it's how I think about users. Consumer behavior, market segmentation, messaging frameworks — these aren't separate from UX research, they're the same discipline from a different angle. I run qualitative interviews, usability tests, and observational sessions. I read Amplitude dashboards and Hotjar heatmaps. But the real value is connecting them: a heatmap tells you where users click, an interview tells you why they're clicking the wrong thing, and a marketing lens tells you what mental model they arrived with. I never start designing without defining the success metric first. Not \"users will like it\" — a number, a threshold, a timeline. Project context →  JAVHD — tested 100+ landing page variants across different acquisition niches. Each variant had a defined conversion hypothesis. Top performers were rolled into a templated system, reducing future production from days to hours per variant.",
    "body_ru": "Маркетинг + дизайн = исследования, которые цепляются. 100+ A/B лендингов, кач + количество, Amplitude · Mixpanel · Hotjar. Интервью, юзабилити, сессии; связка heatmap + интервью + messaging. Метрика успеха до макета — число, порог, срок. Кейс JAVHD — 100+ вариантов лендингов с гипотезами; лучшие ушли в шаблонную систему."
  },
  "information-architecture": {
    "title_en": "Information Architecture & Interaction Design",
    "title_ru": "Информационная архитектура и interaction design",
    "body_en": "Complex systems that feel simple to use CRM · SaaS · Dashboards · Multi-platform Edge cases designed, not ignored 50+ monetization screens Dense data and complex workflows are where a lot of designers struggle. I find them interesting. The challenge isn't making something pretty — it's making something navigable when there are hundreds of data points, nested states, and user roles with different mental models. My toolkit: clear information hierarchy, progressive disclosure, consistent interaction patterns, and honest empty states. I design for the error case as carefully as the success case. A skeleton screen that lies about loading time is a UX debt. An error message that says \"Something went wrong\" is a trust problem. I also think in platforms — the same flow behaves differently on iOS, Android, and web, and pretending otherwise is how you ship something that works in Figma and breaks in prod. Project context →  Corgday HR CRM — HR specialists were drowning in multi-step forms and nested table data. Restructured the information architecture around their actual workflow (not the database schema). Slack-alert module reduced manual status follow-ups by about 40% inside the holding company.",
    "body_ru": "Сложные системы, которые ощущаются простыми. CRM, SaaS, дашборды, мультиплатформа; edge cases спроектированы, 50+ монетизационных экранов. Иерархия, progressive disclosure, паттерны, честные empty/error states, скелетоны с контекстом. Кейс Corgday HR CRM — IA вокруг реального HR-потока, Slack-алерты сократили ручные follow-ups ~40%."
  },
  "design-systems": {
    "title_en": "Design Systems & Scalability",
    "title_ru": "Дизайн-системы и масштабирование",
    "body_en": "One library. Twenty products. Five minutes to launch. −60% frontend handoff time 20+ products from 1 library White Label: days → 5 min launch A design system is only as good as the time it saves. I've built one that became the operational backbone for an entire product portfolio — tokens, Atomic Design structure, documented component states, versioning, and a handoff setup that developers actually use rather than ignore. The real test was the White Label template built on top of Gate19's system. A non-technical admin could launch a fully branded site in under 5 minutes. That's not a design flex — that's a business result. That same system became the foundation for an AI-powered landing generation pipeline. I care about the unglamorous parts: naming conventions, spacing scales, what happens when a component breaks in an unexpected context. A design system that only works in ideal conditions isn't a system — it's a mood board. Project context →  Gate19 — unified component library across 20+ products reduced frontend handoff time by 60% and cut per-product launch time to under 1 week. White Label layer reduced site launch from several days to 5 minutes with zero developer involvement.",
    "body_ru": "Одна библиотека, 20 продуктов, запуск за минуты. −60% времени хэнд-оффа фронту, white label с Gate19: нетехнический админ запускает брендированный сайт <5 минут. Токены, Atomic Design, версии, документация. Кейс Gate19 — единая библиотека на 20+ продуктов, запуск нового UI < недели."
  },
  "ai-workflow": {
    "title_en": "AI-Augmented Design Workflow",
    "title_ru": "AI-аугментированный дизайн-процесс",
    "body_en": "Not a user of AI tools — a builder of AI pipelines Brief → publish: days → hours ~5× faster creative iteration Live on 20+ products Most designers say they \"use AI.\" I build production pipelines with it. There's a difference. Over the past two years I've moved from experimenting with generative models to running them in actual production: Cursor agents handling landing page generation end-to-end, n8n workflows automating asset delivery, ComfyUI and Recraft integrated into creative review cycles. The goal was always the same — compress the time between brief and shipped output without compressing the quality. The part I'm most proud of: I rolled this stack out to the design team as a built-in competency. Not \"here's a tool you can try\" — structured onboarding, documented workflows, real adoption. Because an AI workflow that only one person knows how to use is a single point of failure. Project context →  Landing pipeline (PNB Agency) — Cursor agents + generative models reduced landing production from several days to a few hours. Running live across 20+ products. Creative generator reduced iteration cycles approximately 5× compared to manual asset production.",
    "body_ru": "Не просто «пользуюсь AI», а строю продакшн-пайплайны: Cursor-агенты, n8n, ComfyUI/Recraft в цикле ревью. Brief → публикация за часы, ~5× быстрее итерации, на 20+ продуктах. Внедрение стека в команду как продукт: онбординг, доки, метрики adoption. Кейс PNB — лендинги из дней в часы."
  },
  "agentive-ux": {
    "title_en": "Agentive UX — Designing for AI Agents",
    "title_ru": "Agentive UX — проектирование для AI-агентов",
    "body_en": "When the product acts on its own, UX becomes about trust AI character generation flows Human-in-the-loop validation Real-time agent control UI Agentive UX is the discipline most product teams don't know they need yet. When an AI is taking actions — generating content, making decisions, executing tasks — the design problem shifts from \"how do users do this?\" to \"how do users trust, understand, and correct this?\" Three questions drive every design decision in agentic systems: Does the user understand what the agent is about to do? Can they intervene before it's too late? Can they recover cleanly when it goes wrong? Transparency, controllability, and graceful failure are the new interaction primitives — and they're harder to design well than a checkout flow. I've worked on this in the context of generative AI products where users direct AI behavior in real time, and in internal tooling where agents automate production workflows. The mental models are different. The stakes of getting it wrong are higher. Project context →  ShugarAi — designed generation flows where users direct AI character behavior in real time. Focused on control clarity: what the agent is doing, what can be changed mid-generation, and how to set expectations without a wall of instructions.",
    "body_ru": "Когда продукт действует сам, UX про доверие и контроль. Генерация персонажей, human-in-the-loop, UI реального времени. Три вопроса: понятно ли, что сделает агент; можно ли вмешаться; как откатиться. Кейс ShugarAi — потоки, где пользователь направляет AI в реальном времени."
  },
  "design-ops": {
    "title_en": "Design Ops — Processes & Team Metrics",
    "title_ru": "Design Ops — процессы и метрики команды",
    "body_en": "Design that scales needs systems, not just talent −60% handoff time (measured) 20+ parallel products managed AI stack rollout to full team Design Ops is what happens when you take operations seriously inside a design team. Not project management with a different name — actual measurement of design team throughput, identification of bottlenecks, and systematic reduction of friction in the production cycle. At PNB Agency I built this from scratch across a portfolio of 20+ concurrent products: standardized component library, handoff protocols, review cadences, quality gates before anything reached engineering. The −60% handoff time wasn't a side effect — it was the goal, and we measured it. I also treat process change as a design problem. Rolling out a new AI workflow to a design team is a product launch: you need onboarding, documentation, feedback loops, and adoption metrics. I've done this once. It worked. Project context →  PNB Agency design operations — built processes, tooling and rituals for a cross-product design team running 20+ products simultaneously. Reduced handoff time by 60%. Rolled out AI production stack with full team adoption, measurable output improvement.",
    "body_ru": "Масштабирование дизайна — системы, не только таланты. −60% handoff (замерено), 20+ параллельных продуктов, выкатка AI-стека всей команде. В PNB: библиотека, протоколы хэнд-оффа, ревью-ритуалы, quality gates. Изменение процесса как дизайн-задача с онбордингом и метриками."
  },
  "ecosystem": {
    "title_en": "End-to-End Product Ecosystem Design",
    "title_ru": "End-to-end экосистемы продукта",
    "body_en": "The whole journey, not the prettiest screen Full funnel: entry → retention → win-back 3+ complete product ecosystems Monetization · Streaming · Live · Re-engagement A lot of designers are great at individual screens. Fewer can hold the entire user journey in their head while designing any single part of it. I've designed complete product ecosystems: entry points, activation flows, paywall logic, streaming experiences, retention mechanics, and win-back sequences. Not as separate projects — as one coherent system where every decision in the onboarding affects the retention rate three weeks later. The discipline this requires is knowing which stage is the actual bottleneck. A beautiful onboarding that feeds a broken monetization screen is a waste of everyone's time. I start from the metric that matters most and design backwards from there. Project context →  JAVHD — designed the complete product ecosystem: acquisition landing → activation → streaming → live video → retention loops → re-engagement. Each stage had an owner metric. Gamified onboarding contributed to measurable trial-to-paid conversion growth.",
    "body_ru": "Весь путь пользователя, а не один красивый экран. Воронка: вход → удержание → win-back; 3+ экосистемы; монетизация, стриминг, live, ре-енгейджмент. Кейс JAVHD — лендинг → активация → стриминг → live → удержание; у каждого этапа своя метрика."
  },
  "cross-functional": {
    "title_en": "Cross-functional Leadership",
    "title_ru": "Кросс-функциональное лидерство",
    "body_en": "Fluent in PM, engineering, marketing, and analytics 3 yrs cross-product team leadership Multi-stakeholder alignment Roadmap co-ownership with PM The best design work I've done happened because I was in the room when the product decision was made — not after. I've worked deeply embedded with PMs, engineers, marketers, and analysts. I know how to run a design review that ends with a decision, not a list of feedback. I know how to present to a stakeholder who has five minutes and cares about one number. I know how to tell an engineer that a design needs to change because of new data — and have that conversation not be a problem. Design leadership at the senior level isn't about making final calls. It's about building enough shared understanding that the team makes better decisions whether you're in the room or not. Project context →  PNB Agency — led design across a cross-product team for 3 years, managing stakeholder alignment across multiple concurrent product lines. Co-owned roadmap prioritization with PM. Ran design reviews, sprint planning participation, and executive presentations.",
    "body_ru": "В комнате, где принимается продуктовое решение, а не после. 3 года кросс-командного лидерства в PNB: PM, инженеры, маркетинг, аналитика; ревью с исходом «решение», а не список правок. Кейс PNB — выравнивание стейкхолдеров на нескольких линейках продуктов, совместный роадмап с PM."
  },
  "mentorship": {
    "title_en": "Mentorship & Design Education",
    "title_ru": "Менторство и преподавание",
    "body_en": "Teaching made me a sharper designer Thousands of students reached CONTENTED · Skillbox Junior → mid-level growth track I've been building and teaching design curricula for two of Russia's largest online design schools since 2020. What I got from that is something you can't fake: the ability to explain why something works, not just that it does. Mentoring forces precision. When a junior designer shows you a layout that feels wrong and asks why, \"it feels off\" doesn't cut it. You have to name the principle, connect it to the user's goal, and show how to fix it. That process made me a better designer. Inside product teams, I mentor through work — reviewing decisions, asking the question the designer didn't think to ask, and modeling what good product thinking looks like in practice. I also rolled out AI workflow training to a design team from scratch: structured, documented, with real adoption outcomes. Project context →  CONTENTED (4 years) + Skillbox (2024–present) — developed and taught graphic design and UX/UI curricula. Reached thousands of students across both platforms. Adapted and onboarded junior mentors, ran public workshops and marketing sessions for prospective students.",
    "body_ru": "Преподавание делает дизайнера точнее. Тысячи студентов, CONTENTED · Skillbox, трек junior → mid. С 2020 — программы графдизайна и UX/UI; менторство через работу и онбординг младших менторов. Кейс CONTENTED (4 года) + Skillbox (2024–наст.) — курсы, адаптация менторов, масштаб аудитории."
  }
};
})();